services:
    operaton:
        image: operaton/operaton:1.1.1
        container_name: operaton
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://postgres:5432/operaton
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgrespassword
            - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
            - MANAGEMENT_ENDPOINT_INFO_ENABLED=true
            - OPERATON_BPM_AUTO-DEPLOYMENT-ENABLED=false
            - OPERATON_BPM_HISTORY-LEVEL=ACTIVITY
            - OPERATON_BPM_ADMIN-USER_ID=eoepca
            - OPERATON_BPM_ADMIN-USER_PASSWORD=eoepca
        ports:
        - "9090:8080"
        networks:
            - operaton-network
        depends_on:
            - postgres
        restart: always

    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            - POSTGRES_DB=operaton
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgrespassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - operaton-network
        restart: always

    harvester-worker-landsat:
        image: eoepca/registration-harvester:latest
        container_name: registration-harvester-landsat
        ports:
            - "8081:8080"
        environment:
            - CONFIG_FILE_PATH=/worker/config/harvester.yaml
            - OPERATON_REST_USER=${OPERATON_REST_USER}
            - OPERATON_REST_PASSWORD=${OPERATON_REST_PASSWORD}
            - M2M_USER=${M2M_USER}
            - M2M_PASSWORD=${M2M_PASSWORD}
            - IAM_CLIENT_ID=${IAM_CLIENT_ID}
            - IAM_CLIENT_SECRET=${IAM_CLIENT_SECRET}
        volumes:
            - ./config-landsat.yaml:/worker/config/harvester.yaml:ro
            - /eodata:/eodata:rw            
        restart: always

    harvester-worker-sentinel:
        image: eoepca/registration-harvester:latest
        container_name: registration-harvester-sentinel
        ports:
            - "8082:8080"
        environment:
            - CONFIG_FILE_PATH=/worker/config/harvester.yaml
            - OPERATON_REST_USER=${OPERATON_REST_USER}
            - OPERATON_REST_PASSWORD=${OPERATON_REST_PASSWORD}
            - CDSE_USER=${CDSE_USER}
            - CDSE_PASSWORD=${CDSE_PASSWORD}
            - IAM_CLIENT_ID=${IAM_CLIENT_ID}
            - IAM_CLIENT_SECRET=${IAM_CLIENT_SECRET}
        volumes:
            - ./config-sentinel.yaml:/worker/config/harvester.yaml:ro
            - /eodata:/eodata:rw
        restart: always
    
    harvester-worker-stac:
        image: eoepca/registration-harvester:latest
        container_name: registration-harvester-stac
        ports:
            - "8083:8080"
        environment:
            - CONFIG_FILE_PATH=/worker/config/harvester.yaml
            - OPERATON_REST_USER=${OPERATON_REST_USER}
            - OPERATON_REST_PASSWORD=${OPERATON_REST_PASSWORD}
            - IAM_CLIENT_ID=${IAM_CLIENT_ID}
            - IAM_CLIENT_SECRET=${IAM_CLIENT_SECRET}
        volumes:
            - ./config-static-catalog.yaml:/worker/config/harvester.yaml:ro
        restart: always

    harvester-worker-tutorial:
        image: eoepca/registration-harvester:latest
        container_name: registration-harvester-tutorial
        ports:
            - "8083:8080"
        environment:
            - CONFIG_FILE_PATH=/worker/config/harvester.yaml
            - OPERATON_REST_USER=${OPERATON_REST_USER}
            - OPERATON_REST_PASSWORD=${OPERATON_REST_PASSWORD}
        volumes:
            - ./config-tutorial.yaml:/worker/config/harvester.yaml:ro
        restart: always                

networks:
  operaton-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local