flowable: 

worker:
  topics:
    sentinel_discover_data:
      module: worker.sentinel.tasks
      handler: SentinelDiscoverHandler
    sentinel_download_data:
      module: worker.sentinel.tasks
      handler: SentinelDownloadHandler
    sentinel_unzip:
      module: worker.sentinel.tasks
      handler: SentinelUnzipHandler
    sentinel_check_integrity:
      module: worker.sentinel.tasks
      handler: SentinelCheckIntegrityHandler
    sentinel_extract_metadata:
      module: worker.sentinel.tasks
      handler: SentinelExtractMetadataHandler
    sentinel_register_metadata:
      module: worker.sentinel.tasks
      handler: SentinelRegisterMetadataHandler


  handlers:
    SentinelDiscoverHandler:
      subscription_config:
        number_of_retries: 10

    SentinelDownloadHandler:
      subscription_config:
        number_of_retries: 20
        lock_duration: PT30M  # 30 minute lock duration
      handler_config:
        base_dir: /tmp/sentinel
        retryTimeout: 10

    SentinelUnzipHandler:
      subscription_config:
        number_of_retries: 10
        lock_duration: PT10M  # 10 minute lock duration

    SentinelCheckIntegrityHandler:
      subscription_config:
        number_of_retries: 10
        lock_duration: PT10M  # 10 minute lock duration

    SentinelExtractMetadataHandler:
      subscription_config:
        number_of_retries: 10
        lock_duration: PT5M  # 5 minute lock duration

    SentinelRegisterMetadataHandler:
      subscription_config:
        number_of_retries: 10
        lock_duration: PT5M  # 5 minute lock duration
      handler_config:
        api_url: ""
        api_user: ""
        api_pw: ""