flowable: 

worker:
  topics:
    sentinel_discover_data:
      module: worker.sentinel.tasks
      handler: SentinelDiscoverHandler
    sentinel_download_data:
      module: worker.sentinel.tasks
      handler: SentinelDownloadHandler

  handlers:
    SentinelDiscoverHandler:
      subscription_config:
        number_of_retries: 10

    SentinelDownloadHandler:
      subscription_config:
        number_of_retries: 20
      handler_config:
        download_timeout: 10
        base_dir: /data/sentinel

