from flowable.external_worker_client.external_worker_acquire_job_response import ExternalWorkerAcquireJobResponse
from flowable.external_worker_client.worker_result import WorkResult
from flowable.external_worker_client import WorkerResultBuilder

ExternalJob = ExternalWorkerAcquireJobResponse
JobResultBuilder = WorkerResultBuilder
JobResult = WorkResult
